//+build !noasm !appengine
// AUTO-GENERATED BY C2GOASM -- DO NOT EDIT

TEXT ·_crmdnAsUint64(SB), $0-8


    LONG $0xf0c70f48             // rdrand    rax
    MOVQ AX, v+0(FP)
    RET




TEXT ·_crmdnAsUint32(SB), $0-8


    WORD $0xc70f; BYTE $0xf0     // rdrand    eax
    MOVQ AX, v+0(FP)
    RET




TEXT ·_crmdnAsUint16(SB), $0-8


    LONG $0xf0c70f66             // rdrand    ax
    MOVQ AX, v+0(FP)
    RET
